apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-storefront-api
spec:
  selector:
    matchLabels:
      app: vue-storefront-api
  template:
    metadata:
      labels:
        app: vue-storefront-api
    spec:
      containers:
      - name: vue-storefront-api
        image: divante/vue-storefront-api:latest
        envFrom:
        - configMapRef:
            name: vue-storefront-api-config
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/www/var
          name: code
        - mountPath: /var/www/dist
          name: dist
      volumes:
      - name: code
        emptyDir:
          medium: Memory
      - name: dist
        emptyDir:
          medium: Memory
