---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vue-storefront-volume-claim
spec:
  storageClassName: cinder-high-speed
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
